debug bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,5 +1,3 @@
-#!/bin/sh
-
 #!/bin/bash
 
 # Save this file as ~/.config/yadm/bootstrap and make it executable. It will
@@ -11,15 +9,20 @@ set -eu
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
+
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
     echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
     exit 1
 fi
 
-find "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
+find "$BOOTSTRAP_D" -type f -o -type l | sort | while IFS= read -r bootstrap; do
+    echo "Executing '${bootstrap}"
+    if [[ -x "${bootstrap}" && ! "${bootstrap}" =~ "##" && ! "${bootstrap}" =~ "~$" ]]; then
+	bash "${bootstrap}"
+	retval=$?
+
+	if [ ${retval} -ne 0 ]; then
+            echo "Error: bootstrap '$bootstrap' failed with error code ${retval}" >&2
             exit 1
         fi
     fi
